# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1

###

# Аутентификация предустановленного суперадмина 'starter':
# токен:   eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MDYwMzAyLCJleHAiOjE3MTQxNDY3MDJ9.Ssy2eMd_Xsrrj5zSI-plB21MOXd6EhKzTIw0xrBhWUS9VvJcd4IisPgbXHs4QYgX
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "admin.starter@gmail.ru" ,
  "password": "7410"
}

###

# Регистрация учетной записи
POST {{baseUrl}}/user/reg
auth-token:
Content-Type: application/json

{
  "nickname": "king" ,
  "email": "knhel7@gmail.com" ,
  "password": "123456" ,
  "role": "USER"
}

###

# Аутентификация   eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJrbmhlbDdAZ21haWwuY29tIiwiaWF0IjoxNzE0MDE0NTYwLCJleHAiOjE3MTQxMDA5NjB9.APCq3-P51ls9z8Ev2sHfglEPrOUwU884-Uip_Hi7769pW_QaxVzrCIYvMfe319xn
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel7@gmail.com" ,
  "password": "123456"
}

###

# Выход из учетной записи
POST {{baseUrl}}/logout
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTI0MjUyLCJleHAiOjE3MTQxMjQ4NTJ9.fsf3z5ENVx9oxyQD9AaSGWUiwGMZYI3sNRmQLt12T27lhMeLeMLEfFo7jzuBKxgw
Content-Type: : application/json

###

# Регистрация учетной записи
POST {{baseUrl}}/user/reg
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTQ4OTQyLCJleHAiOjE3MTQxNDk1NDJ9.mY3EmNVUHZx3rbbNByj7SSvDzWtHerEBG_C32HDJd2-eFQSxnPju09Pf3afxzpje
Content-Type: application/json

{
  "nickname": "king2" ,
  "email": "knhel77@gmail.com" ,
  "password": "1234567" ,
  "role": "ADMIN"
}

###

# Аутентификация   eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJrbmhlbDc3QGdtYWlsLmNvbSIsImlhdCI6MTcxNDAxNTE2MSwiZXhwIjoxNzE0MTAxNTYxfQ.4lWpHst-vGXgsvsPNs-hvwEWqUh7U5T8l-tjgUROcL98o0vOJEXKp58GSedRCmPd
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel77@gmail.com" ,
  "password": "1234567"
}

###

# с параметрами ???
GET {{baseUrl}}/logout?username=user1&password=11111
Accept: application/json

###
