# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1

###

# Аутентификация предустановленного суперадмина 'starter':
# токен:   eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTk4ODc2LCJleHAiOjE3MTQxOTkxNzZ9.iGjaVY9N0wXL3lCelOK3dNw9MxBbNPcxPYZ9HSckTI-aWdbjfmihaDA0KQ6UdEv2
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "admin.starter@gmail.ru" ,
  "password": "7410"
}

###

# Регистрация учетной записи
POST {{baseUrl}}/user/reg
auth-token:
Content-Type: application/json

{
  "nickname": "king" ,
  "email": "knhel7@gmail.com" ,
  "password": "123456" ,
  "role": "USER"
}

###

# Аутентификация
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel7@gmail.com" ,
  "password": "123456"
}

###

# Выход из учетной записи
POST {{baseUrl}}/logout
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTI0MjUyLCJleHAiOjE3MTQxMjQ4NTJ9.fsf3z5ENVx9oxyQD9AaSGWUiwGMZYI3sNRmQLt12T27lhMeLeMLEfFo7jzuBKxgw
Content-Type: : application/json

###

# Регистрация учетной записи администратора супер-админом
POST {{baseUrl}}/user/reg
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJrbmhlbDdAZ21haWwuY29tIiwiaWF0IjoxNzE0NjAwNTc5LCJleHAiOjE3MTQ2MDExNzl9.QkelOR21ZvgLNq1NqVV3j3_zyJCYHNOLZnmh4Xsa8ujBDY7Nc7-SYbDZM-E3Jg8c
Content-Type: application/json

{
  "nickname": "king2" ,
  "email": "knhel77@gmail.com" ,
  "password": "1234567" ,
  "role": "ADMIN"
}

###

# Аутентификация
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel77@gmail.com" ,
  "password": "1234567"
}

###
