# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/list

###

# Получение списка файлов:
GET {{baseUrl}}?limit=0
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0NDM3MjI5LCJleHAiOjE3MTQ0Mzc4Mjl9.J-bwevBo1ZE8SSXmB-Wukf90KGnQC30HCC2ITYUF0fqS0TxC5kF4eNkxzkw2q5FZ
Content-Type: application/json

###
