# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/list

###

# Получение списка файлов:
GET {{baseUrl}}?limit=0
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0Mjc3ODQyLCJleHAiOjE3MTQyNzg0NDJ9.IjuMyJu5B6u95ZznmnuD-IMoi6GS-jCZngXx2DwlRHmGtArQ7tW0UVVwVJCvn7ri
Content-Type: application/json

###
