# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/file

###

# Переименование файла:
PUT {{baseUrl}}?filename=example1.txt
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MzAyMjIxLCJleHAiOjE3MTQzMDQwMjF9.b8IU1A3Rdd6Y5owbIIV8N7lqMqBnaQwnAMKCuzxZlRDUQL4RbJv2_AV1Su4Le4zN
Content-Type: application/json

{
  "name": "example2.txt"
}

###
