# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/file

###

# Переименование файла:
PUT {{baseUrl}}?filename=example1.txt
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MzU4MTEwLCJleHAiOjE3MTQzNTk5MTB9.ZWEjMN-SUKNTu2bxCUBpDbQUTGzWE9vVELXnQAeT3if64wFd0a8EB1iXvERh9GtC
Content-Type: application/json

{
  "name": "example2.txt"
}

###

# Удаление файла:
DELETE {{baseUrl}}?filename=example2.txt
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MzU4MTEwLCJleHAiOjE3MTQzNTk5MTB9.ZWEjMN-SUKNTu2bxCUBpDbQUTGzWE9vVELXnQAeT3if64wFd0a8EB1iXvERh9GtC

###
