# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/list

###

# Получение списка файлов:
POST {{baseUrl}}/file?filename=example1.txt
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MjkwMTI4LCJleHAiOjE3MTQyOTE5Mjh9.csCooBaXGYfWltK8ose3yNRUo2_ZiiLxs5kB0k8RwgtDSDkt_VTZ_QYugQK1RDXo
Content-Type: multipart/form-data

###
