# примеры API-запросов

 @baseUrl = http://localhost:5060/api/v1/list

###

# Получение списка файлов:
GET {{baseUrl}}?limit=0
auth-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTUwNjAyLCJleHAiOjE3MTQxNTEyMDJ9.Dqz6-XthRMCKf4Q_NFz2R9c_cRwQKC6IY1gx0WVOw9nbodrjvIJyKwX-gweYxgWW
Content-Type: application/json

###
