# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1/list

###

# Получение списка файлов:
GET {{baseUrl}}?limit=0
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0OTA3MjI5LCJleHAiOjE3MTQ5MDc4Mjl9.peqC8cNYGfGjy-ltxeFV7r70HfvUPqJzvwGJW54YiiS2Lb1u1Ju6IcyCcHdTdTTj
Content-Type: application/json

###
