# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1

###

# Аутентификация предустановленного суперадмина 'starter':
# токен:   eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0MTk4ODc2LCJleHAiOjE3MTQxOTkxNzZ9.iGjaVY9N0wXL3lCelOK3dNw9MxBbNPcxPYZ9HSckTI-aWdbjfmihaDA0KQ6UdEv2
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "admin.starter@gmail.ru" ,
  "password": "7410"
}

###

# Регистрация учетной записи
POST {{baseUrl}}/user
auth-token:
Content-Type: application/json

{
  "nickname": "king" ,
  "email": "knhel7@gmail.com" ,
  "password": "123456" ,
  "role": "USER"
}

###

# Аутентификация
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel7@gmail.com" ,
  "password": "123456"
}

###

# Выход из учетной записи
POST {{baseUrl}}/logout
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0NjkxODcyLCJleHAiOjE3MTQ2OTI0NzJ9.emW9PjeMmDs5iWY3FM7Ryz7klUeJmVm6RKX81EHMxnW-uMKFTJWT59h3ZYNwONKd
Content-Type: : application/json

###

# Регистрация учетной записи администратора супер-админом
POST {{baseUrl}}/user
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0NjkxODcyLCJleHAiOjE3MTQ2OTI0NzJ9.emW9PjeMmDs5iWY3FM7Ryz7klUeJmVm6RKX81EHMxnW-uMKFTJWT59h3ZYNwONKd
Content-Type: application/json

{
  "nickname": "king2" ,
  "email": "knhel77@gmail.com" ,
  "password": "1234567" ,
  "role": "ADMIN"
}

###

# Аутентификация
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "knhel77@gmail.com" ,
  "password": "1234567"
}

###
