# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1

###

# Регистрация учетной записи
POST {{baseUrl}}/user
Content-Type: application/json

{
  "nickname": "king" ,
  "email": "knhel7@gmail.com" ,
  "password": "123456" ,
  "role": "USER"
}

###

# Регистрация учетной записи администратора супер-админом
POST {{baseUrl}}/user
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE1Nzc1Nzk4LCJleHAiOjE3MTU3NzYzOTh9.YknO-ap-B2yIC5CxBvtdAxK3avHjmBEkMybDANY-qPgJWpYmMNjYpgAzAPkLMNAH
Content-Type: application/json

{
  "nickname": "king2" ,
  "email": "knhel77@gmail.com" ,
  "password": "1234567" ,
  "role": "ADMIN"
}

###

# Редактировать свою учетную запись
PUT {{baseUrl}}/user
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJrbmhlbDc3QGdtYWlsLmNvbSIsImlhdCI6MTcxNTc0MjMwNywiZXhwIjoxNzE1NzQyOTA3fQ.tWALMx4tSQULZ4N38prx4Bj1MoxyfsqRkdaAQuglMuoYdQdsmHp7g_QYOonsxllr
Content-Type: application/json

{
  "email": "knhel77@gmail.com" ,
  "password": "1234567"
}

###

# Получить свою учетную запись
GET {{baseUrl}}/user
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJrbmhlbDdAZ21haWwuY29tIiwiaWF0IjoxNzE1Nzc3MDY3LCJleHAiOjE3MTU3Nzc2Njd9.FC_6_t-Hme7nfS_f7YyB52s4ERURWzJ3X2TaxiLvb_Gf0d9z9VkaWz2B1HtLHvh7
Content-Type: application/json

###

# Получить учетную запись по id
GET {{baseUrl}}/user/2
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE1Nzc3NzQ2LCJleHAiOjE3MTU3NzgzNDZ9.34JI2UhmgSprLtk6GLD8-yELGBkp6J0zNbZuhvszSVTs73L0IgXE645W9R9nk1qb
Content-Type: application/json

###

# Удалить свою учетную запись
DELETE {{baseUrl}}/user
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE1NzQyNjY3LCJleHAiOjE3MTU3NDMyNjd9.e1UHJlvyQyFK_cpP_gW_LqxOI8JhXv8eMaNfda9niS6gStHdtj0AqoK9Dz5oaIKM
Content-Type: application/json

###

# Удалить учетную запись по id
DELETE {{baseUrl}}/user/2
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE1Nzc3NzQ2LCJleHAiOjE3MTU3NzgzNDZ9.34JI2UhmgSprLtk6GLD8-yELGBkp6J0zNbZuhvszSVTs73L0IgXE645W9R9nk1qb
Content-Type: application/json

###
