# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1/file

###

# Переименование файла:
PUT {{baseUrl}}?filename=example1.txt
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0ODA2NTE0LCJleHAiOjE3MTQ4MDcxMTR9.PVLgeF469F2-BLIsnrykIv94kv9XdfILNX56fMTfI-B2uKtN2t4acRxNcGNcSYLJ
Content-Type: application/json

{
  "name": "example2.txt"
}

###

# Удаление файла:
DELETE {{baseUrl}}?filename=example2.txt
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0ODA3MjA3LCJleHAiOjE3MTQ4MDc4MDd9.bNf5cbQNd96Sd56a9tmiTmL8OHoQzKsmllFhaDZDKHhuPVjbM8jHGxozifefrj9O

###
