# примеры API-запросов

 @baseUrl = http://localhost:5055/api/v1/list

###

# Получение списка файлов:
GET {{baseUrl}}?limit=0
auth-token: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbi5zdGFydGVyQGdtYWlsLnJ1IiwiaWF0IjoxNzE0ODA4NDg1LCJleHAiOjE3MTQ4MDkwODV9.Fwry9LKEjZCa8If-gl299bYPwt22a6v1tAZRgklvQ1PiT8Ey7L59hj4EeV7RnYde
Content-Type: application/json

###
